# Generated by Django 3.2.3 on 2021-07-03 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaUniverso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proceso', models.CharField(max_length=50)),
                ('macroproceso', models.CharField(max_length=50)),
                ('responsableProceso', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=8)),
                ('auditoriaGeneral', models.CharField(max_length=50)),
                ('nombreAuditoria', models.CharField(max_length=50)),
                ('actividadAuditoria', models.CharField(max_length=150)),
            ],
        ),
    ]
