# Generated by Django 3.2.3 on 2021-07-04 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Universo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MacroprocesosUniverso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('macroproceso', models.CharField(max_length=50)),
                ('responsable', models.CharField(max_length=50)),
            ],
        ),
    ]
