# Generated by Django 3.2.3 on 2021-07-18 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Universo', '0003_procesosuniverso'),
    ]

    operations = [
        migrations.CreateModel(
            name='GestionResponsableUniverso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsable', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='procesosuniverso',
            name='responsable',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='auditoriauniverso',
            name='macroproceso',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='auditoriauniverso',
            name='proceso',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='macroprocesosuniverso',
            name='macroproceso',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='macroprocesosuniverso',
            name='responsable',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='procesosuniverso',
            name='macroproceso',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='procesosuniverso',
            name='proceso',
            field=models.CharField(max_length=100),
        ),
    ]
